- hosts: webservers
  become: yes 
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello World!"
  tasks:
    - include_tasks: apache/tasks.yml
  handlers:
    - include_tasks: apache/handler.yml
  